apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
  namespace: gitlab-runner
  annotations:
    fluxcd.io/ignore: "false"
    linkerd.io/inject: enabled
  labels:
    type: local
spec:
  volumeMode: Filesystem
  storageClassName: standard
  hostPath:
    path: /data/gitlab-runner/
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 4Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: minio-pv-claim
    namespace: gitlab-runner
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pv-claim
  namespace: gitlab-runner
  annotations:
    fluxcd.io/ignore: "false"
    linkerd.io/inject: enabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi