apiVersion: v1
data:
  values.yaml: |
    existingSecret: "minio"
    persistence:
      existingClaim: "minio-pv-claim"
    defaultBucket:
      enabled: true
      name: "cache"
      policy: none
      purge: false
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: minio-values-config
  namespace: gitlab-runner
