apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: minio
  namespace: gitlab-runner
  annotations:
    fluxcd.io/ignore: "false"
spec:
  releaseName: minio
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: minio
    version: 5.0.11
  valuesFrom:
  - secretKeyRef:
      name: minio-values-secrets
      key: values.yaml
  - configMapKeyRef:
        name: minio-values-config
        key: values.yaml