apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secrets
  namespace: gitlab-runner
spec:
  encryptedData:
    secretKey: AgCKwBW2Rzz5o9qbNbpvBpbtysS2b/b37AP3n1mskyKWKfgfyISIKJm8O/1F6E+eYNJTKVwCGxZLgM18ITG7U74qOKqLap4ckgMxX6NPkPHvUfCoMYnIHgCxjshPKiqddUe1t3GejPBVPKT9KFIB/F/bHNyBJJoHZOEDFLYquMoQGeih8w8jOpTG/aCVsfrZdrfs8qSesTMNfHLRy5XudlQ0rOl9vko75ohY9B84syDNp8tuKQ009eZy8KSYz8iIZ8/bTEQ76/+ipjluDvosavPqHkfPYuxWZeVgfwKU5LVrOarFLtNEf6J4KWzGYXClL9vRuKzm73JT1ROt7lhjOqyI/GBN6Y4yB/lmyTmj+v5Ah8cwfDhxc6bEmtUMCsDKxD7Xrps0AAeqKKTbwHmS/pEBikM1IyBTE24snoAN2nzdCkCmM3zaEf+hxMsty74jfzz1RfF4acCRoAdBqKhDLmc98eBh0Q/FpZJrEy5haSH0s6SZlaBb6Sz8lXgXu76ZmsQezTW/iYnyDSuG9JvKLyjUjetB0mQamwrtLBuSXvpXRrrzJS3oFKY9l1RVAVabE63t/+Wjc17GHkbrhN4vVmqIyr3kSWyNE23x9XnTKFZcVVwreJmQ1pfk/J/T0g9+xVIcKTfE+rXPSuJN48IBxlsQ5GrzngL8QTHOpQYC1Rpwgs2yFkOIuijtHs+76yoqq/guFqyJY60+4GxbqUc=
  template:
    metadata:
      creationTimestamp: null
      name: minio-secrets
      namespace: gitlab-runner
status: {}

