apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secrets
  namespace: prod
spec:
  encryptedData:
    secretKey: AgC0tARxMTR8o3Pn/RO+QSwohET5DDvuEqI5bCDwXfqxkViVSHqN9JXCPn2RYd61d1VdH/B8GosCVtL2+y/33hnBjwfgDAT6lpXSch5Y+D5fBhAIJ+T5Eqrw88Ttk4bwwnW3Z5Ib1kMD8S7oWwGBJHQVsi09rj4UXiRi5e12PYw4aE7KiCqyuVk+LnnMHYFbnybBTIXEU2swp1/MKpDHNRu8GayCymaXepwRQpfPDL+Nkz5MlmzDHDu/YbLCPKs45a/joWpNe6Dja5qHstyXZzCtj2/emFmWOrOUjnSpLsFhNnGUJsm6iADSLsHUNM/P45E9utHQmQVeFWpmZAx3uCnM0EPZouLLgwoo9GBLxeh+PaBPhAbjA64OZquGeVSv/wW5m3eYCSzVYkShlzNoXozHEXvUgoOke2hQWX2VU5Mm6lZcQvnAqUqrGA5KMAVQ7uvIdpnrj7LkkCBp6izJdZzykIG8JgXrlfomgVk+qp3GYNLLrAl7G0SzwhFFL8COt4GDXARaKIrkbK8G6s8kCWNScev9lhBGoB9N1ArZIBwx5P1alQOgobx9/DRA81sGWIHjHwm9se3zYpr/uq+/8ktDNud/m8srlaqze8uAqiNg8uT04aHqJnSj5Hxn8jlfuqRUz0ilREkwv3nTdA84oCk6mJyv7cvVMV3OLpwfZTcnxcg1d8+PbzQ7O0swBev+HPjW4rA1MFN99tOA50E=
  template:
    metadata:
      creationTimestamp: null
      name: minio-secrets
      namespace: prod
status: {}

